use_frameworks!

platform :ios, '12.0'

target 'BizConfSDK_Example' do
  pod 'BizConfSDK', :path => '../'

  target 'BizConfSDK_Tests' do
    inherit! :search_paths
    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        
      # no signing for pods bundle, after xcode 14
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
        
      # reset libs version
      deployment = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']

      if deployment.to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end

      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
